export const Productos = [
  {
    id: 1,
    nombre: "mueble rojo",
    precio: 6.0,
    cantidad: 1,
    categoria: "rojo",
    stock: 1,
    img: "https://web.mueblescolonialclub.com/wp-content/uploads/2020/12/mueble-auxiliar-lujo-contract-muebles-colonial-club-vlc.jpg",
  },
  {
    id: 2,
    nombre: "mueble amarillo",
    precio: 6.0,
    cantidad: 1,
    categoria: "amarillo",
    stock: 1,
    img: "https://web.mueblescolonialclub.com/wp-content/uploads/2020/12/aparador-lujo-contract-muebles-colonial-club-vlc.jpg",
  },
  {
    id: 3,
    nombre: "mueble azul",
    precio: 6.0,
    cantidad: 1,
    categoria: "azul",

    stock: 1,
    img: "https://casaydiseno.com/wp-content/uploads/2018/02/bello-contraste-blanco-salones.jpg",
  },
  {
    id: 4,
    nombre: "mueble blanco",
    precio: 6.0,
    cantidad: 1,
    categoria: "blanco",
    img: "https://casaydiseno.com/wp-content/uploads/2018/02/muebles-bonitos-elegantes-tradicionales.jpg",

    stock: 1,
  },
  {
    id: 5,
    nombre: "mueble anaranjado",
    precio: 6.0,
    cantidad: 1,
    categoria: "anaranjada",
    stock: 1,
    img: "https://i.pinimg.com/originals/3d/62/79/3d6279d1548523d80825d26c9f7d7d94.jpg",
  },
  {
    id: 6,
    nombre: "mueble anaranjado",
    precio: 6.0,
    cantidad: 1,
    categoria: "anaranjada",
    stock: 1,
    img: "    https://casaydiseno.com/wp-content/uploads/2018/02/muebles-bonitos-concepto-moderno.jpg",
  },
  {
    id: 6,
    nombre: "mueble anaranjado",
    precio: 6.0,
    cantidad: 1,
    categoria: "anaranjada",
    stock: 1,
    img: "    https://www.mueblesbonitos.com/media/wysiwyg/04_navidad_alessia_530x335.jpg",
  },
  {
    id: 6,
    nombre: "mueble anaranjado",
    precio: 6.0,
    cantidad: 1,
    categoria: "anaranjada",
    stock: 1,
    img: "      https://casaydiseno.com/wp-content/uploads/2018/02/muebles-bonitos-elegantes-letras.jpg    ",
  },
];
